name: Push Helm Chart to GHR

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version tag'
        required: true
        default: 'latest' 
        type: string

env:
  HELM_EXPERIMENTAL_OCI: 1 #enable OCI support
  HELM_VERSION_TO_INSTALL: 3.11.0 # version of HELM to install

jobs:

  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          # Version of helm
          version: ${{ env.HELM_VERSION_TO_INSTALL }} # default is latest

      - name: Push Helm chart to OCI compatible registry (Github)
        uses: bsord/helm-push@v4.1.0
        with:
          useOCIRegistry: true
          registry-url:  oci://ghcr.io/${{ github.repository }}
          username: ${{ github.repository_owner }}
          access-token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          chart-folder: app01