name: Push Helm Chart to GHR

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version tag'
        required: true
        default: 'latest' 
        type: string

jobs:

  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Push Helm chart to Chartmuseum
        uses: bsord/helm-push@v4.1.0
        with:
          registry-url: http://chart.20.103.115.121.nip.io
          username: ${{ secrets.CHART_USER }}
          password: ${{ secrets.CHART_PASSWD }}
          force: true
          chart-folder: app01

      # - name: Push Helm chart to OCI compatible registry (Github)
      #   uses: bsord/helm-push@v4.1.0
      #   with:
      #     useOCIRegistry: true
      #     registry-url:  oci://ghcr.io/${{ github.repository }}
      #     username: ${{ github.repository_owner }}
      #     access-token: ${{ secrets.GITHUB_TOKEN }}
      #     force: true
      #     chart-folder: app01
