name: Push Helm Chart to GHR

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version tag'
        required: true
        default: 'latest' 
        type: string

env:
  HELM_EXPERIMENTAL_OCI: 1 #enable OCI support
  HELM_VERSION_TO_INSTALL: 3.11.0 # version of HELM to install
  GCR_IMAGE: ghcr.io/${{ github.repository_owner }}/app01

  jobs:
  build:
    name: publish gcr
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
        name: checkout repo
      
      - name: install helm
        uses: Azure/setup-helm@v1
        with:
          # Version of helm
          version: ${{ env.HELM_VERSION_TO_INSTALL }} # default is latest

      - name: login to acr using helm
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ env.GCR_IMAGE }} --username ${{ github.repository_owner }} --password-stdin

      - name: save helm chart to local registry
        run: |
          helm chart save ${{ github.workspace }}/app01/ ${{ env.GCR_IMAGE }}:${{ github.sha }}

      - name: publish chart to acr
        run: |
          helm chart push ${{ env.GCR_IMAGE }}:${{ github.sha }}