name: Push Helm Chart to GHR

on:
  # push:
  #   branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ARGO_SERVER: argocd.20.103.115.121.nip.io
  CHART_FOLDER: app01

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Push Helm chart to Chartmuseum
        uses: bsord/helm-push@v4.1.0
        with:
          registry-url: https://chart.20.103.115.121.nip.io
          username: ${{ secrets.CHART_USER }}
          password: ${{ secrets.CHART_PASSWD }}
          force: true
          chart-folder: ${{ env.CHART_FOLDER }}

      - name: List files
        run: |
          ls -lrt .

      - name: Get Chart version
        run: |
          echo $CHART_FOLDER
          echo $ARGO_SERVER
          echo "$CHART_FOLDER"
          echo "$ARGO_SERVER"
          echo "CHART_VERSION=$(helm show chart $CHART_FOLDER | grep ^version | awk '{ print $2 }')" >> "GITHUB_ENV"

      - name: Setup ArgoCD CLI 
        uses: imajeetyadav/argocd-cli@v1
        with:
          version: v2.7.1 # optional 
      
      - name: Check Argo CD CLI version
        run: |
          argocd version --client
          argocd login $ARGO_SERVER --username {{ secret.ARGO_USER }} --password {{ secret.ARGO_PASSWD }}
          echo "argocd app set argocd/demoapp01 --project default --revision $CHART_VERSION"

      # - name: Push Helm chart to OCI compatible registry (Github)
      #   uses: bsord/helm-push@v4.1.0
      #   with:
      #     useOCIRegistry: true
      #     registry-url:  oci://ghcr.io/${{ github.repository }}
      #     username: ${{ github.repository_owner }}
      #     access-token: ${{ secrets.GITHUB_TOKEN }}
      #     force: true
      #     chart-folder: app01
